// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvpujviwqlmctmniidyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2cHVqdml3cWxtY3RtbmlpZHl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MzA4NzMsImV4cCI6MjA1OTEwNjg3M30.ccI13NiJbFW5mIamR2fCjl1CCJWt8ZgMQ1HDJWQbCAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);